# Site
repository: HyunaShin/modern-resume-theme
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: 신현아
title: Teamlab, 가천대학교 — 학부생 연구원(2018.07 - 현재)
email: hyuna1615@gmail.com
phone: 010-7756-8590

# Social links
github_username:  HyunaShin
facebook_username:
linkedin_username: hyuna-shin-465a81171

# About Section
# about_title: About Me (Use this to override about section title)
# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image:  ./assets/images/self_photo.jpg
about_content: | # this will include new lines to allow paragraphs

  다양한 도메인의 특성에 맞는 Data Engineering을 통한 데이터 분석, 인사이트 도출 경험 다수
 
  연구 환경 개선을 위한 협업 도구 사용 및 파이프라인 구축 경험
 
  “습득의 완성은 설명” - 프로그래밍 기초(2018.09 - 현재) TA , 랩 내부 스터디(<a href = 'http://bitly.kr/ohj67x'>2018.07</a> - <a href ='http://bitly.kr/8z9GkR'>현재</a>) 바벨봇(2018.04 - 2018.06) 
  
# Projects Section
projects_title: Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Experience #(Use this to override about experience section title)

# Education Section
education_title: 논문 #(Use this to override about education section title)

# More Section
more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  - [파티락](http://www.partyrock.co.kr/)(2016.08 - 2018.07) , [MC맨 이벤트](http://www.mcman.co.kr/)(2015.11 - 2016.03) 등에서 [레크레이션 & 돌잔치 MC로서](https://www.youtube.com/watch?v=HgAceSuD9es)한 경험이 있습니다.
  - 위 경험은 발표역량, 팀 내부의 원활한 의사소통에 밑거름이 되었습니다.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

