# Site
repository: HyunaShin/modern-resume-theme
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: 신현아
title: Python Engineer, Teamlab 학부생 연구원
email: hyuna1615@gmail.com
phone: 010-7756-8590

# Social links
github_username:  HyunaShin
facebook_username:
linkedin_username: hyuna-shin-465a81171

# About Section
# about_title: About Me (Use this to override about section title)
# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image:  ./assets/images/self_photo.jpg
about_content: | # this will include new lines to allow paragraphs
  AWS, Jenkins, Docker 등을 사용해 협업, 시스템 자동화에 기여하기 위해 노력했습니다.

  Serverless, 분산 네트워크 환경에서의 개발 및 테스트/배포 자동화 경험이 있으며 더 편리한 개발 환경을 위해 힘쓰고 싶습니다.

  현재 분산 애플리케이션 - 백엔드 스터디를 진행중입니다.

  ### Skills

  - <b>Confident</b>
    - <font size = '4'>OS : Linux, Windows</font>
    - <font size = '4'>Language : Python</font>
    - <font size = '4'>Database : Mysql</font>
    - <font size = '4'>Frameworks : Django, Flask</font>
    - <font size = '4'>Others : Data Analysis, Git</font>


  - <b>Knowledgeable</b>
    - <font size = '4'>OS : Mac </font>
    - <font size = '4'>Language : Java, Matlab </font>
    - <font size = '4'>Database : PostgreSQL</font>
    - <font size = '4'>Others : Data Engineering, Docker, Jenkins , NoSQL </font>


# Projects Section
projects_title: Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Experience #(Use this to override about experience section title)

# Education Section
education_title: Education #(Use this to override about education section title)

# More Section
more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  - [파티락](http://www.partyrock.co.kr/)(2016.08 - 2018.07) , [MC맨 이벤트](http://www.mcman.co.kr/)(2015.11 - 2016.03) 등에서 [레크레이션 & 돌잔치 MC로서](https://www.youtube.com/watch?v=HgAceSuD9es)한 경험이 있습니다.
  - 위 경험은 발표역량, 팀 내부의 원활한 의사소통에 밑거름이 되었습니다.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
